export default function apiLoadCountry() {
    return new Promise((resolve, reject) => {
        setTimeout(() => resolve([
            {id: 163, name: "Champions League"},
            {id: 164, name: "Europa League"},
            {id: 165, name: "UEFA"},
            {id: 166, name: "Copa America"},
            {id: 167, name: "Cup of Nations"},
            {id: 168, name: "International"},
            {id: 169, name: "England"},
            {id: 170, name: "Italy"},
            {id: 171, name: "Spain"},
            {id: 172, name: "Germany"},
            {id: 173, name: "France"},
            {id: 174, name: "Netherlands"},
            {id: 175, name: "Belgium"},
            {id: 176, name: "Portugal"},
            {id: 177, name: "Scotland"},
            {id: 178, name: "World Cup U-20"},
            {id: 179, name: "World Cup U-17"},
            {id: 180, name: "Euro U-21"},
            {id: 181, name: "Euro U-19"},
            {id: 182, name: "Euro U-17"},
            {id: 183, name: "World Cup Women"},
            {id: 184, name: "Euro Women"},
            {id: 185, name: "Austria"},
            {id: 186, name: "Cyprus"},
            {id: 187, name: "Denmark"},
            {id: 188, name: "Finland"},
            {id: 189, name: "Greece"},
            {id: 190, name: "Iceland"},
            {id: 191, name: "Ireland"},
            {id: 192, name: "Luxembourg"},
            {id: 193, name: "Norway"},
            {id: 194, name: "Northern Ireland"},
            {id: 195, name: "Sweden"},
            {id: 196, name: "Switzerland"},
            {id: 197, name: "Turkey"},
            {id: 198, name: "Wales"},
            {id: 199, name: "Belarus"},
            {id: 200, name: "Bosnia & Herz."},
            {id: 201, name: "Bulgaria"},
            {id: 202, name: "Croatia"},
            {id: 203, name: "Czech Republic"},
            {id: 204, name: "Estonia"},
            {id: 205, name: "Hungary"},
            {id: 206, name: "Israel"},
            {id: 207, name: "Latvia"},
            {id: 208, name: "Lithuania"},
            {id: 209, name: "FYR Macedonia"},
            {id: 210, name: "Moldova"},
            {id: 211, name: "Montenegro"},
            {id: 212, name: "Poland"},
            {id: 213, name: "Romania"},
            {id: 214, name: "Russia"},
            {id: 215, name: "Serbia"},
            {id: 216, name: "Slovakia"},
            {id: 217, name: "Slovenia"},
            {id: 218, name: "Ukraine"},
            {id: 219, name: "South America"},
            {id: 220, name: "Argentina"},
            {id: 221, name: "Bolivia"},
            {id: 222, name: "Brazil"},
            {id: 223, name: "Chile"},
            {id: 224, name: "Colombia"},
            {id: 225, name: "Ecuador"},
            {id: 226, name: "Paraguay"},
            {id: 228, name: "Uruguay"},
            {id: 229, name: "Venezuela"},
            {id: 231, name: "Mexico"},
            {id: 232, name: "USA"},
            {id: 233, name: "Costa Rica"},
            {id: 234, name: "El Salvador"},
            {id: 235, name: "Guatemala"},
            {id: 236, name: "Honduras"},
            {id: 239, name: "China"},
            {id: 240, name: "India"},
            {id: 242, name: "Japan"},
            {id: 244, name: "Singapore"},
            {id: 245, name: "Thailand"},
            {id: 247, name: "Armenia"},
            {id: 248, name: "Azerbaijan"},
            {id: 249, name: "Georgia"},
            {id: 250, name: "Kazakhstan"},
            {id: 253, name: "Australia"},
            {id: 254, name: "New Zealand"},
            {id: 256, name: "Algeria"},
            {id: 257, name: "Egypt"},
            {id: 259, name: "Morocco"},
            {id: 260, name: "South Africa"},
            {id: 261, name: "Tunisia"},
            {id: 262, name: "Albania"},
            {id: 264, name: "Faroe Islands"},
            {id: 267, name: "Malta"},
            {id: 272, name: "Canada"},
            {id: 277, name: "Jamaica"},
            {id: 285, name: "Hong Kong"},
            {id: 287, name: "Jordan"},
            {id: 289, name: "Malaysia"},
            {id: 299, name: "Uzbekistan"},
            {id: 336, name: "Uganda"}
        ]), 700);
    })
}
